// Code generated by scripts/generate_specs.py. DO NOT EDIT.
package protocol

import (
	"fmt"
	"math"
)

const (
	Version = "1"
	Ack = "ack"
	Error = "error"
	SeedHello = "seed.hello"
	GardenHello = "garden.hello"
	SeedRegister = "seed.register"
	GardenRegistered = "garden.registered"
	SeedResume = "seed.resume"
	GardenResume = "garden.resume"
	SeedCapabilities = "seed.capabilities"
	SeedStatus = "seed.status"
	SeedHeartbeat = "seed.heartbeat"
	GardenHeartbeatAck = "garden.heartbeat_ack"
	SeedMetrics = "seed.metrics"
	SeedWarning = "seed.warning"
	SeedActivity = "seed.activity"
	GardenLeaseExtended = "garden.lease_extended"
	GardenLeaseWarning = "garden.lease_warning"
	GardenLeaseExpiring = "garden.lease_expiring"
	CommandStart = "command.start"
	CommandAccepted = "command.accepted"
	CommandStarted = "command.started"
	CommandStdout = "command.stdout"
	CommandStderr = "command.stderr"
	CommandStdin = "command.stdin"
	CommandStdinAccepted = "command.stdin.accepted"
	CommandCancel = "command.cancel"
	CommandKill = "command.kill"
	CommandExit = "command.exit"
	CommandFailed = "command.failed"
	CommandCancelled = "command.cancelled"
	CommandKilled = "command.killed"
	FileRead = "file.read"
	FileWrite = "file.write"
	FileEdit = "file.edit"
	FileStat = "file.stat"
	FileSearch = "file.search"
	FileList = "file.list"
	FileDelete = "file.delete"
	FileMkdir = "file.mkdir"
	FileResult = "file.result"
	FileChunk = "file.chunk"
	FileError = "file.error"
	PtyCreate = "pty.create"
	PtyInput = "pty.input"
	PtyResize = "pty.resize"
	PtyClose = "pty.close"
	PtyCreated = "pty.created"
	PtyOutput = "pty.output"
	PtyExit = "pty.exit"
	PtyError = "pty.error"
	PortOpen = "port.open"
	PortClose = "port.close"
	PortDescribe = "port.describe"
	PortOpened = "port.opened"
	PortClosed = "port.closed"
	PortStatus = "port.status"
	ArtifactUpload = "artifact.upload"
	ArtifactDownload = "artifact.download"
	SnapshotCreate = "snapshot.create"
	ArtifactReady = "artifact.ready"
	ArtifactFailed = "artifact.failed"
	SnapshotCreated = "snapshot.created"
	GardenDrain = "garden.drain"
	SeedDraining = "seed.draining"
	GardenShutdown = "garden.shutdown"
	SeedGoodbye = "seed.goodbye"
)

type FieldSpec struct {
	Type     string
	Required bool
	Enum     []string
}

type MessageSpec struct {
	Capability string
	Direction  string
	Fields     map[string]FieldSpec
}

var MessageSpecs = map[string]MessageSpec{
	"ack": {Capability: "core", Direction: "bidirectional", Fields: map[string]FieldSpec{
			"status": {Type: "string", Required: true, Enum: []string{"accepted", "rejected", "duplicate", "unsupported"}},
		}},
	"error": {Capability: "core", Direction: "bidirectional", Fields: map[string]FieldSpec{
			"code": {Type: "string", Required: true, Enum: nil},
			"message": {Type: "string", Required: true, Enum: nil},
			"retryable": {Type: "boolean", Required: true, Enum: nil},
			"details": {Type: "map", Required: false, Enum: nil},
			"failed_message_id": {Type: "string", Required: false, Enum: nil},
		}},
	"seed.hello": {Capability: "session", Direction: "inbound", Fields: map[string]FieldSpec{
			"seed_version": {Type: "string", Required: true, Enum: nil},
			"protocol_version": {Type: "string", Required: true, Enum: nil},
			"platform": {Type: "string", Required: true, Enum: nil},
			"arch": {Type: "string", Required: true, Enum: nil},
			"hostname": {Type: "string", Required: true, Enum: nil},
			"session_key": {Type: "string", Required: true, Enum: nil},
		}},
	"garden.hello": {Capability: "session", Direction: "outbound", Fields: map[string]FieldSpec{
			"protocol_version": {Type: "string", Required: true, Enum: nil},
			"session_id": {Type: "string", Required: true, Enum: nil},
			"sandbox_id": {Type: "string", Required: true, Enum: nil},
			"heartbeat_interval_ms": {Type: "integer", Required: true, Enum: nil},
			"ack_timeout_ms": {Type: "integer", Required: true, Enum: nil},
		}},
	"seed.register": {Capability: "session", Direction: "inbound", Fields: map[string]FieldSpec{
			"seed_id": {Type: "string", Required: true, Enum: nil},
			"seed_version": {Type: "string", Required: true, Enum: nil},
			"platform": {Type: "string", Required: true, Enum: nil},
			"arch": {Type: "string", Required: true, Enum: nil},
			"hostname": {Type: "string", Required: true, Enum: nil},
			"boot_time": {Type: "string", Required: false, Enum: nil},
			"workspace_root": {Type: "string", Required: false, Enum: nil},
			"process_id": {Type: "integer", Required: false, Enum: nil},
		}},
	"garden.registered": {Capability: "session", Direction: "outbound", Fields: map[string]FieldSpec{
			"session_id": {Type: "string", Required: true, Enum: nil},
			"sandbox_id": {Type: "string", Required: true, Enum: nil},
			"lease_expires_at": {Type: "string", Required: false, Enum: nil},
			"max_session_duration_ms": {Type: "integer", Required: false, Enum: nil},
		}},
	"seed.resume": {Capability: "session", Direction: "inbound", Fields: map[string]FieldSpec{
			"session_id": {Type: "string", Required: true, Enum: nil},
			"sandbox_id": {Type: "string", Required: true, Enum: nil},
			"last_garden_seq_seen": {Type: "integer", Required: true, Enum: nil},
			"last_seed_seq_sent": {Type: "integer", Required: true, Enum: nil},
			"seed_id": {Type: "string", Required: true, Enum: nil},
			"connection_generation": {Type: "integer", Required: true, Enum: nil},
		}},
	"garden.resume": {Capability: "session", Direction: "outbound", Fields: map[string]FieldSpec{
			"status": {Type: "string", Required: true, Enum: []string{"ok", "replace_session", "rejected"}},
			"session_id": {Type: "string", Required: true, Enum: nil},
			"replay_from_seed_seq": {Type: "integer", Required: false, Enum: nil},
			"replay_from_garden_seq": {Type: "integer", Required: false, Enum: nil},
		}},
	"seed.capabilities": {Capability: "session", Direction: "inbound", Fields: map[string]FieldSpec{
			"commands": {Type: "boolean", Required: true, Enum: nil},
			"stdin": {Type: "boolean", Required: true, Enum: nil},
			"cancel": {Type: "boolean", Required: true, Enum: nil},
			"kill": {Type: "boolean", Required: true, Enum: nil},
			"files": {Type: "map", Required: false, Enum: nil},
			"pty": {Type: "boolean", Required: true, Enum: nil},
			"metrics": {Type: "boolean", Required: true, Enum: nil},
			"ports": {Type: "boolean", Required: true, Enum: nil},
			"snapshots": {Type: "boolean", Required: true, Enum: nil},
		}},
	"seed.status": {Capability: "session", Direction: "inbound", Fields: map[string]FieldSpec{
			"state": {Type: "string", Required: true, Enum: []string{"booting", "ready", "degraded", "draining"}},
			"hostname": {Type: "string", Required: false, Enum: nil},
			"platform": {Type: "string", Required: false, Enum: nil},
			"arch": {Type: "string", Required: false, Enum: nil},
			"seed_version": {Type: "string", Required: true, Enum: nil},
			"uptime_ms": {Type: "integer", Required: false, Enum: nil},
			"workspace_root": {Type: "string", Required: false, Enum: nil},
			"active_commands": {Type: "integer", Required: false, Enum: nil},
			"network": {Type: "map", Required: false, Enum: nil},
		}},
	"seed.heartbeat": {Capability: "session", Direction: "inbound", Fields: map[string]FieldSpec{
			"uptime_ms": {Type: "integer", Required: true, Enum: nil},
			"active_commands": {Type: "integer", Required: true, Enum: nil},
			"last_garden_seq_seen": {Type: "integer", Required: true, Enum: nil},
			"last_seed_seq_sent": {Type: "integer", Required: true, Enum: nil},
			"load_avg": {Type: "float", Required: false, Enum: nil},
			"memory_used_bytes": {Type: "integer", Required: false, Enum: nil},
			"connection_generation": {Type: "integer", Required: true, Enum: nil},
		}},
	"garden.heartbeat_ack": {Capability: "session", Direction: "outbound", Fields: map[string]FieldSpec{
			"lease_expires_at": {Type: "string", Required: false, Enum: nil},
			"server_time": {Type: "string", Required: true, Enum: nil},
			"status": {Type: "string", Required: true, Enum: []string{"ok", "draining", "reauth_required"}},
		}},
	"seed.metrics": {Capability: "session", Direction: "inbound", Fields: map[string]FieldSpec{
			"cpu_percent": {Type: "float", Required: false, Enum: nil},
			"load_avg_1m": {Type: "float", Required: false, Enum: nil},
			"memory_total_bytes": {Type: "integer", Required: false, Enum: nil},
			"memory_used_bytes": {Type: "integer", Required: false, Enum: nil},
			"disk_total_bytes": {Type: "integer", Required: false, Enum: nil},
			"disk_used_bytes": {Type: "integer", Required: false, Enum: nil},
			"fs_available_bytes": {Type: "integer", Required: false, Enum: nil},
			"rx_bytes": {Type: "integer", Required: false, Enum: nil},
			"tx_bytes": {Type: "integer", Required: false, Enum: nil},
			"sampled_at": {Type: "string", Required: true, Enum: nil},
		}},
	"seed.warning": {Capability: "session", Direction: "inbound", Fields: map[string]FieldSpec{
			"code": {Type: "string", Required: true, Enum: nil},
			"message": {Type: "string", Required: true, Enum: nil},
			"details": {Type: "map", Required: false, Enum: nil},
		}},
	"seed.activity": {Capability: "session", Direction: "inbound", Fields: map[string]FieldSpec{
			"kind": {Type: "string", Required: true, Enum: []string{"command_output", "stdin", "file_op", "session_active"}},
			"command_id": {Type: "string", Required: false, Enum: nil},
			"at": {Type: "string", Required: true, Enum: nil},
		}},
	"garden.lease_extended": {Capability: "lease", Direction: "outbound", Fields: map[string]FieldSpec{
			"lease_expires_at": {Type: "string", Required: true, Enum: nil},
			"reason": {Type: "string", Required: true, Enum: nil},
		}},
	"garden.lease_warning": {Capability: "lease", Direction: "outbound", Fields: map[string]FieldSpec{
			"lease_expires_at": {Type: "string", Required: true, Enum: nil},
			"remaining_ms": {Type: "integer", Required: true, Enum: nil},
		}},
	"garden.lease_expiring": {Capability: "lease", Direction: "outbound", Fields: map[string]FieldSpec{
			"lease_expires_at": {Type: "string", Required: true, Enum: nil},
			"remaining_ms": {Type: "integer", Required: true, Enum: nil},
			"action": {Type: "string", Required: true, Enum: nil},
		}},
	"command.start": {Capability: "commands", Direction: "outbound", Fields: map[string]FieldSpec{
			"command_id": {Type: "string", Required: true, Enum: nil},
			"command": {Type: "string", Required: true, Enum: nil},
			"cwd": {Type: "string", Required: false, Enum: nil},
			"env": {Type: "map", Required: false, Enum: nil},
			"stdin": {Type: "boolean", Required: false, Enum: nil},
			"timeout_ms": {Type: "integer", Required: false, Enum: nil},
			"metadata": {Type: "map", Required: false, Enum: nil},
		}},
	"command.accepted": {Capability: "commands", Direction: "inbound", Fields: map[string]FieldSpec{
			"command_id": {Type: "string", Required: true, Enum: nil},
			"state": {Type: "string", Required: true, Enum: []string{"queued", "starting"}},
		}},
	"command.started": {Capability: "commands", Direction: "inbound", Fields: map[string]FieldSpec{
			"command_id": {Type: "string", Required: true, Enum: nil},
			"pid": {Type: "integer", Required: true, Enum: nil},
			"started_at": {Type: "string", Required: true, Enum: nil},
		}},
	"command.stdout": {Capability: "commands", Direction: "inbound", Fields: map[string]FieldSpec{
			"command_id": {Type: "string", Required: true, Enum: nil},
			"chunk": {Type: "string", Required: true, Enum: nil},
			"encoding": {Type: "string", Required: true, Enum: nil},
			"stream_seq": {Type: "integer", Required: true, Enum: nil},
		}},
	"command.stderr": {Capability: "commands", Direction: "inbound", Fields: map[string]FieldSpec{
			"command_id": {Type: "string", Required: true, Enum: nil},
			"chunk": {Type: "string", Required: true, Enum: nil},
			"encoding": {Type: "string", Required: true, Enum: nil},
			"stream_seq": {Type: "integer", Required: true, Enum: nil},
		}},
	"command.stdin": {Capability: "commands", Direction: "outbound", Fields: map[string]FieldSpec{
			"command_id": {Type: "string", Required: true, Enum: nil},
			"data": {Type: "string", Required: true, Enum: nil},
			"encoding": {Type: "string", Required: true, Enum: nil},
		}},
	"command.stdin.accepted": {Capability: "commands", Direction: "inbound", Fields: map[string]FieldSpec{
			"command_id": {Type: "string", Required: true, Enum: nil},
			"bytes": {Type: "integer", Required: true, Enum: nil},
		}},
	"command.cancel": {Capability: "commands", Direction: "outbound", Fields: map[string]FieldSpec{
			"command_id": {Type: "string", Required: true, Enum: nil},
			"grace_period_ms": {Type: "integer", Required: true, Enum: nil},
			"escalation": {Type: "string", Required: true, Enum: []string{"kill"}},
		}},
	"command.kill": {Capability: "commands", Direction: "outbound", Fields: map[string]FieldSpec{
			"command_id": {Type: "string", Required: true, Enum: nil},
			"signal": {Type: "string", Required: false, Enum: nil},
		}},
	"command.exit": {Capability: "commands", Direction: "inbound", Fields: map[string]FieldSpec{
			"command_id": {Type: "string", Required: true, Enum: nil},
			"exit_code": {Type: "integer", Required: true, Enum: nil},
			"completed_at": {Type: "string", Required: true, Enum: nil},
		}},
	"command.failed": {Capability: "commands", Direction: "inbound", Fields: map[string]FieldSpec{
			"command_id": {Type: "string", Required: true, Enum: nil},
			"exit_code": {Type: "integer", Required: false, Enum: nil},
			"message": {Type: "string", Required: true, Enum: nil},
			"completed_at": {Type: "string", Required: true, Enum: nil},
		}},
	"command.cancelled": {Capability: "commands", Direction: "inbound", Fields: map[string]FieldSpec{
			"command_id": {Type: "string", Required: true, Enum: nil},
			"completed_at": {Type: "string", Required: true, Enum: nil},
		}},
	"command.killed": {Capability: "commands", Direction: "inbound", Fields: map[string]FieldSpec{
			"command_id": {Type: "string", Required: true, Enum: nil},
			"signal": {Type: "string", Required: false, Enum: nil},
			"completed_at": {Type: "string", Required: true, Enum: nil},
		}},
	"file.read": {Capability: "files", Direction: "outbound", Fields: map[string]FieldSpec{

		}},
	"file.write": {Capability: "files", Direction: "outbound", Fields: map[string]FieldSpec{

		}},
	"file.edit": {Capability: "files", Direction: "outbound", Fields: map[string]FieldSpec{

		}},
	"file.stat": {Capability: "files", Direction: "outbound", Fields: map[string]FieldSpec{

		}},
	"file.search": {Capability: "files", Direction: "outbound", Fields: map[string]FieldSpec{

		}},
	"file.list": {Capability: "files", Direction: "outbound", Fields: map[string]FieldSpec{

		}},
	"file.delete": {Capability: "files", Direction: "outbound", Fields: map[string]FieldSpec{

		}},
	"file.mkdir": {Capability: "files", Direction: "outbound", Fields: map[string]FieldSpec{

		}},
	"file.result": {Capability: "files", Direction: "inbound", Fields: map[string]FieldSpec{

		}},
	"file.chunk": {Capability: "files", Direction: "inbound", Fields: map[string]FieldSpec{

		}},
	"file.error": {Capability: "files", Direction: "inbound", Fields: map[string]FieldSpec{

		}},
	"pty.create": {Capability: "pty", Direction: "outbound", Fields: map[string]FieldSpec{

		}},
	"pty.input": {Capability: "pty", Direction: "outbound", Fields: map[string]FieldSpec{

		}},
	"pty.resize": {Capability: "pty", Direction: "outbound", Fields: map[string]FieldSpec{

		}},
	"pty.close": {Capability: "pty", Direction: "outbound", Fields: map[string]FieldSpec{

		}},
	"pty.created": {Capability: "pty", Direction: "inbound", Fields: map[string]FieldSpec{

		}},
	"pty.output": {Capability: "pty", Direction: "inbound", Fields: map[string]FieldSpec{

		}},
	"pty.exit": {Capability: "pty", Direction: "inbound", Fields: map[string]FieldSpec{

		}},
	"pty.error": {Capability: "pty", Direction: "inbound", Fields: map[string]FieldSpec{

		}},
	"port.open": {Capability: "ports", Direction: "outbound", Fields: map[string]FieldSpec{

		}},
	"port.close": {Capability: "ports", Direction: "outbound", Fields: map[string]FieldSpec{

		}},
	"port.describe": {Capability: "ports", Direction: "outbound", Fields: map[string]FieldSpec{

		}},
	"port.opened": {Capability: "ports", Direction: "inbound", Fields: map[string]FieldSpec{

		}},
	"port.closed": {Capability: "ports", Direction: "inbound", Fields: map[string]FieldSpec{

		}},
	"port.status": {Capability: "ports", Direction: "inbound", Fields: map[string]FieldSpec{

		}},
	"artifact.upload": {Capability: "artifacts", Direction: "outbound", Fields: map[string]FieldSpec{

		}},
	"artifact.download": {Capability: "artifacts", Direction: "outbound", Fields: map[string]FieldSpec{

		}},
	"snapshot.create": {Capability: "artifacts", Direction: "outbound", Fields: map[string]FieldSpec{

		}},
	"artifact.ready": {Capability: "artifacts", Direction: "inbound", Fields: map[string]FieldSpec{

		}},
	"artifact.failed": {Capability: "artifacts", Direction: "inbound", Fields: map[string]FieldSpec{

		}},
	"snapshot.created": {Capability: "artifacts", Direction: "inbound", Fields: map[string]FieldSpec{

		}},
	"garden.drain": {Capability: "control", Direction: "outbound", Fields: map[string]FieldSpec{
			"reason": {Type: "string", Required: true, Enum: nil},
			"deadline": {Type: "string", Required: false, Enum: nil},
		}},
	"seed.draining": {Capability: "control", Direction: "inbound", Fields: map[string]FieldSpec{
			"active_commands": {Type: "integer", Required: true, Enum: nil},
			"estimated_completion_ms": {Type: "integer", Required: false, Enum: nil},
		}},
	"garden.shutdown": {Capability: "control", Direction: "outbound", Fields: map[string]FieldSpec{
			"reason": {Type: "string", Required: true, Enum: nil},
			"deadline": {Type: "string", Required: false, Enum: nil},
		}},
	"seed.goodbye": {Capability: "control", Direction: "inbound", Fields: map[string]FieldSpec{
			"reason": {Type: "string", Required: true, Enum: nil},
			"final_command_count": {Type: "integer", Required: false, Enum: nil},
			"sent_at": {Type: "string", Required: true, Enum: nil},
		}},
}

func ValidatePayload(msgType string, payload map[string]any) error {
	spec, ok := MessageSpecs[msgType]
	if !ok {
		return fmt.Errorf("unknown message type: %s", msgType)
	}
	for name, field := range spec.Fields {
		value, present := payload[name]
		if field.Required && !present {
			return fmt.Errorf("%s missing required field %s", msgType, name)
		}
		if !present {
			continue
		}
		if !matchesType(field.Type, value) {
			return fmt.Errorf("%s field %s must be %s", msgType, name, field.Type)
		}
		if len(field.Enum) > 0 {
			s, ok := value.(string)
			if !ok {
				return fmt.Errorf("%s field %s must be string enum", msgType, name)
			}
			matched := false
			for _, allowed := range field.Enum {
				if s == allowed {
					matched = true
					break
				}
			}
			if !matched {
				return fmt.Errorf("%s field %s has invalid value %q", msgType, name, s)
			}
		}
	}
	return nil
}

func matchesType(kind string, value any) bool {
	switch kind {
	case "string":
		_, ok := value.(string)
		return ok
	case "boolean":
		_, ok := value.(bool)
		return ok
	case "map":
		switch value.(type) {
		case map[string]any, map[string]string:
			return true
		default:
			return false
		}
	case "float":
		switch value.(type) {
		case float64, float32:
			return true
		default:
			return false
		}
	case "integer":
		switch v := value.(type) {
		case int, int8, int16, int32, int64, uint, uint8, uint16, uint32, uint64:
			return true
		case float64:
			return math.Trunc(v) == v
		case float32:
			return float32(math.Trunc(float64(v))) == v
		default:
			return false
		}
	default:
		return true
	}
}
